
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'

export const FETCHING_PIZZA_BY_NAME = 'FETCHING_PIZZA_BY_NAME'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'